services:

  ContoBancario\Application\Conto\Service\CreaConto:
    arguments:
      $contoCorrenteRepository: '@ContoBancario\Domain\Conto\Repository\ContoCorrenteRepository'

  ContoBancario\Application\Conto\Service\ContoCorrenteService:
    abstract: true
    arguments:
      - '@ContoBancario\Domain\Conto\Repository\TransazioneRepository'
      - '@ContoBancario\Domain\Conto\Repository\ContoCorrenteRepository'

  ContoBancario\Application\Conto\Service\VersaService:
    parent: ContoBancario\Application\Conto\Service\ContoCorrenteService

  ContoBancario\Application\Conto\Service\PrelevaService:
    parent: ContoBancario\Application\Conto\Service\ContoCorrenteService
