parameters:
  # Adds a fallback DATABASE_URL if the env var is not set.
  # This allows you to run cache:warmup even if your
  # environment variables are not available yet.
  # You should not need to change this value.
  env(DATABASE_URL): ''

doctrine:
  dbal:
    # configure these for your database server
    driver: 'pdo_mysql'
    server_version: '5.7'
    charset: utf8
    default_table_options:
      charset: utf8
      collate: utf8_general_ci
    url: '%env(resolve:DATABASE_URL)%'
    types:
      IdConto: ContoBancario\Infrastructure\Domain\ContoCorrente\Doctrine\MySql\Aggregate\DoctrineIdConto
      IdTransazione: ContoBancario\Infrastructure\Domain\ContoCorrente\Doctrine\MySql\Aggregate\DoctrineIdTransazione

  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    #naming_strategy: doctrine.orm.naming_strategy.underscore
    #auto_mapping: true
    entity_managers:
      default:
        mappings:
          AppDoctrine:
            is_bundle: false
            type: yml
            dir: "%kernel.project_dir%/src/ContoBancario/Infrastructure/Application/Persistence/Doctrine/Mapping/Aggregate"
            prefix: ContoBancario\Domain
