#!/usr/bin/env /bin/zsh

while test $# -gt 0
do
    case "$1" in
        --force)
            #Altro comando
            ./sf doctrine:database:drop --force --if-exists
            ;;
        #--opt2) echo "option 2"
        #    ;;
        #--*) echo "bad option $1"
        #    ;;
        #*) echo "argument $1"
        #    ;;
    esac
    shift
done

./sf doctrine:database:create --if-not-exists
./sf doctrine:migration:migrate --no-interaction

exit 0
