ContoBancario\Domain\ContoCorrente\Aggregate\ContoCorrente:
  type: entity
  table: conti

  id:
    idConto:
      type: IdConto
      column: id

  manyToMany:
    transazioni:
      targetEntity: Transazione
      orphanRemoval: true
      cascade: ["all"]
      fetch: EAGER
      joinTable:
        name: conti_correnti_transazioni
        joinColumns:
          conto_id:
            referencedColumnName: id
        inverseJoinColumns:
          transazione_id:
            referencedColumnName: id
            unique: true

  fields:
    titolare:
      type: string
      nullable: false
    saldo:
      type: integer
      nullable: false
      options:
        default: 0
    maxPrelievi:
      type: integer
      nullable: false
      column: max_prelievi
